clusterName: test-cluster
chartMode: custom
annotations:
  certSecret:
    kubernetes.io/cert-secret: value
highAvailability:
  replicaCount: 3
  certManager:
    enabled: true
    issuerName: letsencrypt
