apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    teleport-role: node
  name: node
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      teleport-role: node
      node: regular
  template:
    metadata:
      labels:
        teleport-role: node
        node: regular
    spec:
      containers:
        - image: ${TELEPORT_IMAGE}
          name: teleport
          args: ["-d", "--insecure"]
          ports:
            - name: nodessh
              containerPort: 3022
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/teleport
              name: config
              readOnly: true
      volumes:
        - configMap:
            name: node-config
          name: config
